<?php
/* -------------------------------------------------------------------------- *\
|* -[ Index - Test ]--------------------------------------------------------- *|
\* -------------------------------------------------------------------------- */
include("template.inc.php");
function content(){
 // check parameter
 if(!$_GET["exe"]){die("TEST DIE");}else{pre_var_dump("TEST STARTED");}
 // build mail object
 $mail=new stdClass();
 $mail->to="manuel.zavatta@cogne.com";
 $mail->subject="test";
 $mail->message="ciaoooo";
 // definitions
 $to_array=explode(";",$mail->to);
 $cc_array=explode(";",$mail->cc);
 $bcc_array=explode(";",$mail->bcc);
 $attachments_array=explode(";",$mail->attachments);
 // requrie php mailer class
 require_once("../core/phpmailer/PHPMailerAutoload.php");
 // build php mailer
 $mailer=new PHPMailer;
 $mailer->CharSet="UTF-8";
 // check for stmp or relay
 if(api_getOption("smtp")){
  $mailer->isSMTP();
  // host
  $mailer->Host=api_getOption("smtp_host");
  // authentication
  if(strlen(api_getOption("smtp_username"))>0){
   $mailer->SMTPAuth=TRUE;
   $mailer->Username=api_getOption("smtp_username");
   $mailer->Password=api_getOption("smtp_password");
  }else{
   $mailer->SMTPAuth=FALSE;
  }
  // secure
  switch(strtolower(api_getOption("smtp_secure"))){
   case "tls":$mailer->SMTPSecure="tls";break;
   case "ssl":$mailer->SMTPSecure="ssl";break;
   default:$mailer->SMTPAutoTLS=FALSE;
  }
 }
 // sender
 if(!strlen($mail->from)){$mail->from=api_getOption('owner_mail');}
 if(!strlen($mail->sender)){$mail->sender=api_getOption('owner_mail_from');}
 $mailer->From=api_getOption('owner_mail');
 $mailer->FromName=stripslashes($mail->sender);
 $mailer->addReplyTo(stripslashes($mail->from));
 // receivers
 if(count($to_array)){foreach($to_array as $to){$mailer->addAddress(trim(stripslashes($to)));}}
 if(count($cc_array)){foreach($cc_array as $cc){$mailer->addCC(trim(stripslashes($cc)));}}
 if(count($bcc_array)){foreach($bcc_array as $bcc){$mailer->addBCC(trim(stripslashes($bcc)));}}
 if(count($attachments_array)){foreach($attachments_array as $attachment){$mailer->addAttachment(trim(stripslashes($attachment)));}}
 // subject
 $mailer->Subject=stripslashes($mail->subject);
 // message
 $mail->message.="\n\n--\nThis message was automatically generated by Coordinator for company ".api_getOption("owner").", please do not respond.";
 if($mail->html){
  $mailer->isHTML(TRUE);
  $mailer->Body=stripslashes(nl2br($mail->message));
  $mailer->AltBody=strip_tags(str_replace("<br>","\n",stripslashes($mail->message)));
 }else{
  $mailer->Body=strip_tags(str_replace("<br>","\n",stripslashes($mail->message)));
 }
 // sendmail
 $sended=$mailer->send();
 // return ok or error
 if(!$sended){pre_var_dump("MAILER ERROR");pre_var_dump($mailer->ErrorInfo);}else{pre_var_dump("MAILER OK");}
 // debug
 pre_var_dump($mailer);
 // END
 pre_var_dump("TEST ENDED");
}
?>